[package]
name = "yggdrasil-ir"
version = "0.1.0"
authors = ["Aster <192607617@qq.com>"]
description = "Yggdrasil Language IR"
repository = "https://github.com/ygg-lang/yggdrasil-rs"
readme = "Readme.md"
license = "MPL-2.0"
edition = "2021"

[dependencies]
character-set = "0.4.0"
regex-automata = { version = "0.2.0", features = ["std"] }
convert_case = "0.6.0"
indexmap = { version = "1.9.1", features = ["serde"] }
ucd-trie = "0.1.5"
ucd-util = "0.1.9"
lazy_static = "1.4.0"
num = { version = "0.4.0", features = ["serde"] }
serde = { version = "1.0.147", features = ["derive"] }
url = { version = "2.3.1", features = ["serde"] }

[dependencies.yggdrasil-error]
version = "0.1.1"
path = "../ygg-error"
features = []
