[package]
name = "yggdrasil-ir"
version = "0.1.2"
authors = ["Aster <192607617@qq.com>"]
description = "Yggdrasil Language IR"
repository = "https://github.com/ygg-lang/yggdrasil-rs"
documentation = "https://docs.rs/yggdrasil-ir"
readme = "Readme.md"
license = "MPL-2.0"
edition = "2021"

[dependencies]
diagnostic-quick = "0.4.0"
character-set = "0.4.0"
regex-automata = { version = "0.2.0", features = ["std"] }
convert_case = "0.6.0"
indexmap = { version = "1.9.2", features = ["serde"] }
ucd-trie = "0.1.5"
ucd-util = "0.1.10"
lazy_static = "1.4.0"
num = { version = "0.4.0", features = ["serde"] }
serde = { version = "1.0.155", features = ["derive"] }
url = { version = "2.3.1", features = ["serde"] }
syn = "2.0.15"
quote = "1.0.27"