[package]
name = "yggdrasil-rt"
version = "0.0.3"
authors = ["Aster <192607617@qq.com>"]
description = "Yggdrasil Shared Structure"
repository = "https://github.com/ygg-lang/yggdrasil-rs"
documentation = "https://docs.rs/yggdrasil-rt"
readme = "Readme.md"
license = "MPL-2.0"
edition = "2021"

[dependencies]

[features]
default = []
#lsp = ["lsp-types", "url"]
