[workspace]
members = ["projects/*"]
default-members = [
    "projects/ygg-bootstrap",
    "projects/ygg-cli",
    "projects/ygg-core",
    "projects/ygg-lsp",
    "projects/ygg-shared",
]
exclude = [
    "projects/.DS_Store",
]

[profile.release]
lto = true
panic = "abort"