[workspace]
resolver = "2"
members = ["projects/*"]
default-members = [
    "projects/ygg-ir",
    "projects/ygg-rt",
]
exclude = [
    "projects/.DS_Store",
]

[profile.release]
lto = true
panic = "abort"