[workspace]
members = ["projects/*"]
default-members = [
    "projects/ygg-cst-shared",
    "projects/ygg-pest",
]
exclude = [
    "projects/.DS_Store",
]

[profile.release]
lto = true
panic = "abort"