[workspace]
members = ["projects/*"]
default-members = [
    "projects/ygg-ir",
#    "projects/ygg-error",
#    "projects/ygg-bootstrap",
]
exclude = [
    "projects/.DS_Store",
]

[profile.release]
lto = true
panic = "abort"