[package]
name = "yggdrasil-core"
description = "Yggdrasil grammar for the tree-sitter parsing library"
version = "0.1.1"
authors = ["Aster <192608617@qq.com>"]
license = "MPL2.0"
readme = "../../readme.md"
keywords = ["incremental", "parsing", "rust"]
categories = ["parsing", "text-editors"]
repository = "https://github.com/ygg-lang/yggdrasil-rs"
edition = "2021"

include = [
    "src/*",
]

[dependencies]
yggdrasil-bootstrap = { version = "0.1", path = "../ygg-bootstrap" }
tokio = { version = "1.21.1", features = ["io-std", "rt-multi-thread", "macros", "test-util"] }
serde_json = "1.0.85"
indexmap = "1.9.1"
convert_case = "0.6.0"
xxhash-rust = { version = "0.8.5", features = ["xxh3"] }
rkyv = "0.7.39"
toml = "0.5.9"
dashmap = "5.4.0"
thiserror = "1.0.35"
anyhow = "1.0.65"
ariadne = "0.1.5"
itertools = "0.10.5"
# same as tower-lsp = "0.14"
lsp-types = { version = "0.93.1", features = ["proposed"], optional = true }
railroad = { version = "0.1.1", optional = true }
lrpeg = { version = "0.4.1", optional = true }

[features]
default = ["lsp", "railroad"]
lsp = ["lsp-types"]

[dev-dependencies]


[build-dependencies]
