[package]
name = "yggdrasil-core"
description = "Yggdrasil grammar for the tree-sitter parsing library"
version = "0.1.1"
authors = ["Aster <192608617@qq.com>"]
license = "MPL2.0"
readme = "../../readme.md"
keywords = ["incremental", "parsing", "rust"]
categories = ["parsing", "text-editors"]
repository = "https://github.com/ygg-lang/yggdrasil-rs"
edition = "2018"

include = [
    "src/*",
]

[dependencies]
tokio = { version = "1.12", features = ["io-std", "rt-multi-thread", "macros", "test-util"] }
# tree-sitter-cli = { version = "0.20", path = "../../../tree-sitter/cli"}
tree-sitter-ygg = { version = "0.2", path = "../tree-sitter-ygg"}
serde_json = "1.0"
indexmap = "1.7"
convert_case = "0.4"
xxhash-rust = { version = "0.8", features = ["xxh3"] }
rkyv = "0.7"
toml = "0.5"
dashmap = "4.0"

# same as tower-lsp = "0.14"
lsp-types = { version = "0.89", features = ["proposed"], optional = true }
tree-sitter = { version = "0.20", optional = true }
tree-sitter-cli = { version = "0.20", optional = true }

[features]
default = ["lsp"]
lsp = ["lsp-types"]
tree-sitter-support = ["tree-sitter", "tree-sitter-cli"]

[dev-dependencies]


[build-dependencies]
