[package]
name = "yggdrasil-error"
version = "0.1.1"
authors = ["Aster <192607617@qq.com>"]
description = "Yggdrasil Shared Structure"
repository = "https://github.com/ygg-lang/yggdrasil-rs"
readme = "Readme.md"
license = "MPL-2.0"
edition = "2021"

[dependencies]
url = "2.3.1"
lsp-types = { version = "0.93.1", features = ["proposed"], optional = true }
peginator = {version = "0.2.5", optional = true}
ropey = {version = "1.5.0", optional = true}
num = {version = "0.4.0", optional = true}


[features]
default = []
