[package]
name = "yggdrasil-error"
version = "0.1.3"
authors = ["Aster <192607617@qq.com>"]
description = "AWSL Window Structure Language"
repository = "https://github.com/ygg-lang/yggdrasil-rs"
readme = "readme.md"
license = "MPL-2.0"
edition = "2021"

[dependencies]
diagnostic = "0.5.3"
# parser
askama = { version = "0.12.1", optional = true }
antlr-rust = { version = "0.3.0-beta", optional = true }
# serde
json5 = { version = "0.4.1", optional = true }
# cli
wax = { version = "0.6.0", optional = true }

[dependencies.validatus]
version = "0.0.2"

[features]
default = []
