[package]
name = "yggdrasil-error"
version = "0.1.2"
authors = ["Aster <192607617@qq.com>"]
description = "Yggdrasil Shared Structure"
repository = "https://github.com/ygg-lang/yggdrasil-rs"
readme = "Readme.md"
license = "MPL-2.0"
edition = "2021"

[dependencies]
diagnostic = "0.3.7"
url = { version = "2.3.1", optional = true }
lsp-types = { version = "0.93.2", features = ["proposed"], optional = true }
peginator = { version = "0.3.0", optional = true }
ropey = { version = "1.5.0", optional = true }
num = { version = "0.4.0", optional = true }
ucd-trie = { version = "0.1.5", optional = true }
sled = { version = "0.34.7", optional = true }

[features]
default = []
