[package]
name = "yggdrasil-cli"
version = "0.1.0"
authors = ["Aster <192607617@qq.com>"]
description = "Yggdrasil Language CLI"
repository = "https://github.com/ygg-lang/yggdrasil-rs"
readme = "Readme.md"
license = "MPL-2.0"
edition = "2018"

[dependencies]
yggdrasil-bootstript = { version = "0.1", path = "../ygg-bootstript" }
clap = "3.0.0-beta.4"